name: CI
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest still not supported by tree-sitter/setup-action@v1
    steps:
      - uses: actions/checkout@v4
      - uses: tree-sitter/setup-action@v1
      - run: tree-sitter generate
      - run: tree-sitter test

